### ISSUE TITLE
Updating `url` should not use "ForceNew"

### ISSUE THREAD

**Issue by drubin** [louy/terraform-provider-uptimerobot#11]
The API supports updating a URL, so it would be great to support this in terraform instead of forcing a recreation of the monitor. 

https://github.com/louy/terraform-provider-uptimerobot/blob/master/uptimerobot/resource_uptimerobot_monitor.go#L30 

Is it as simple as removing this?

**Comment by louy** [comment]
I think it could be that simple, although it'd need testing since the documentation wasn't always reliable

**Comment by louy** [comment]
Fixed in #12
