### ISSUE TITLE
Error when create monitor keyword type

### ISSUE THREAD

**Issue by Mehdi-Mameri** [louy/terraform-provider-uptimerobot#112]
Hi,

Thanks for providing a module for uptimerobot, i have this error log when i want to create monitor type "keyword" : 

```
Error: Got error from UptimeRobot: {"message":"\"keyword_type\" must be one of [1, 2]","parameter_name":"keyword_type","passed_value":"0","type":"invalid_parameter"}
│ 
│   with module.projet.uptimerobot_monitor.monitor["staging-frontend"],
│   on ../modules/uptime-robot/main.tf line 2, in resource "uptimerobot_monitor" "monitor":
│    2: resource "uptimerobot_monitor" "monitor" {
```

there is my configuration files : 
main.tf 

`module "projet" {
  source                          = "../modules/uptime-robot"
  monitor                         = var.projet_monitor
  alert_contact               = uptimerobot_alert_contact.it
  status_page                 = var.projet_status_page
}`

variable.tf

`variable "projet_monitor" {
  default = {
    staging-frontend = {
      name                  = " Staging FrontEnd"
      type                    = "keyword"
      keyword_type    = "not exists"
      keyword_value   = "ok"
      url                       = "https://www.url-here.com/"
      interval               = 60
    }
}`

Someone has already use terraform for monitor keyword ?

terraform version 1.0.7
latest version of provider uptimerobot v0.5.1
Mehdi M.

**Comment by Mehdi-Mameri** [comment]
Do you think its a syntax error on my side ? @louy

**Comment by jerome-morgado** [comment]
Hello,

I have the same issue.
How to implement Keyword checks ?

Regards

**Comment by louy** [comment]
This depends on what you have in your module, which you haven't shared.

Example code from the tests, which currently work:
https://github.com/louy/terraform-provider-uptimerobot/blob/c473457e5f35301b5bbe9c40284b314451810139/uptimerobot/resource_uptimerobot_monitor_test.go#L64-L120

```tf
resource "uptimerobot_monitor" "test" {
  friendly_name = "TF Test: keyword"
  type          = "keyword"
  url           = "https://google.com"
  keyword_type  = "not exists"
  keyword_value = "yahoo"
}
```

**Comment by louy** [comment]
I would assume you forgot to pass `keyword_type` in your `modules/uptime-robot` file

**Comment by Mehdi-Mameri** [comment]
thanks I do some tests right now !!!

**Comment by Mehdi-Mameri** [comment]
you're awesome ! it works.
Thanks again for your work ! and you can close this Issues
