### ISSUE TITLE
uptimerobot_alert_contact isn't outputting id

### ISSUE THREAD

**Issue by tcarrondo** [louy/terraform-provider-uptimerobot#23]
The resource **uptimerobot_alert_contact**  isn't outputting **id**.

**Comment by tcarrondo** [comment]
this makes impossible to:


`
alert_contact {
    id = "${resource.uptimerobot_alert_contact.slack.id}"
    # threshold  = 0  # pro only
    # recurrence = 0  # pro only
  }
`

**Comment by drubin** [comment]
You should not have `resource.` in your example.  It should be `"${uptimerobot_alert_contact.slack.id}"`


Here is a fill example we use in our tests
From https://github.com/louy/terraform-provider-uptimerobot/blob/master/uptimerobot/resource_uptimerobot_monitor_test.go#L130-L144 

```
resource "uptimerobot_alert_contact" "test" {
  friendly_name = "#infrastructure"
  type = "slack"
  value = "https://slack.com/services/xxxx"
}
resource "uptimerobot_monitor" "test" {
  friendly_name = "%s"
  type          = "%s"
  url           = "%s"
  alert_contact {
    id         = "${uptimerobot_alert_contact.test.id}"
    threshold  = 0
    recurrence = 0
  }
}
```

**Comment by tcarrondo** [comment]
@drubin can you, please, link me, in the code, the output `id` of the resource `uptimerobot_alert_contact`?

**Comment by tcarrondo** [comment]
I got it!
you should remove `resource.` from the documentation

**Comment by tcarrondo** [comment]
My bad! thanks for the hint!

**Comment by drubin** [comment]
@tcarrondo Thought I fixed this ages ago...  I noticed it a while ago. 

Here is a PR fixing the issue. Hopefully it will help others.

https://github.com/louy/terraform-provider-uptimerobot/pull/24

**Comment by louy** [comment]
@all-contributors please add @drubin for answering questions

**Comment by louy** [comment]
@all-contributors please add @tcarrondo for bug report
