### ISSUE TITLE
Code has no license

### ISSUE THREAD

**Issue by SpamapS** [louy/terraform-provider-uptimerobot#4]
Hi! I am researching using uptimerobot with terraform, but you haven't placed any evidence that your code has an open source or free license. As a result, I can't even look at the code to look for license headers without tainting myself if I wanted to write my own provider and open source it.

I recommend that you choose a license that suits your intentions so that others can re-use your code.

https://help.github.com/articles/licensing-a-repository/

Cheers!

**Comment by louy** [comment]
Thanks for pointing this out!

Fixed in c98ad2c (using same license as [terraform-provider-aws](https://github.com/terraform-providers/terraform-provider-aws))

**Comment by louy** [comment]
@all-contributors please add @SpamapS for bug
