### ISSUE TITLE
Add install instructions

### ISSUE THREAD

**Issue by epicserve** [louy/terraform-provider-uptimerobot#73]
It's not obvious how you install this 3rd party providor. Can you add some instructions in the README?

**Comment by epicserve** [comment]
The following seems to work, but was a lot of trouble trying to figure out.

## Installing

```
git clone https://github.com/louy/terraform-provider-uptimerobot.git
cd terraform-provider-uptimerobot
export version=0.4.3
export provider_path=registry.terraform.io/louy/uptimerobot/$version/darwin_amd64/
go build -o terraform-provider-uptimerobot_0.4.3
mkdir -p ~/Library/Application\ Support/io.terraform/plugins/$provider_path
cp terraform-provider-uptimerobot_$version  ~/Library/Application\ Support/io.terraform/plugins/$provider_path
```

## Adding the provider

Add the following where your configure your providers:
```
provider "uptimerobot" {
  api_key = var.uptime_robot_key
}

terraform {
  required_providers {
    uptimerobot = {
      source = "louy/uptimerobot"
    }
  }
  required_version = ">= 0.13"
}
``

**Comment by epicserve** [comment]
I was then able to import existing monitors using the uptime robot API method `getMonitors` to get the id.

```
terraform import 'uptimerobot_monitor.websites["Foo"]' <id>
```

I used the following config with exact information redacted.

```
data "uptimerobot_account" "account" {}

locals {
  website_monitors = {
    "Example" = "https://example.com/"
    "Foo" = "https://foo.com"
  }
}

data "uptimerobot_alert_contact" "default_alert_contact" {
  friendly_name = "person@example.com"
}

resource "uptimerobot_monitor" "websites" {
  for_each = local.website_monitors
  friendly_name = each.key
  type          = "http"
  url           = each.value
  interval      = 300

  alert_contact {
    id = data.uptimerobot_alert_contact.default_alert_contact.id
  }

}
```

**Comment by FlxPeters** [comment]
With Terraform 0.13 is't possible to publish a community provider to the Terraform Registry: https://www.terraform.io/docs/registry/providers/publishing.html

The installation of the provider than is much easier. The registration must be done by the repository owner.
Is that what you're gonna do?

**Comment by epicserve** [comment]
@FlxPeters, that sounds like a great solution to me.

cc: @louy

**Comment by louy** [comment]
I'll take a look at the registry thing. Thanks for recommending

As for now, you can grab the compiled binary from the releases page (no need to build from source) and you should be able to place it in the plugins folder like you did. It's a tiny bit easier but not that much i get it

Hopefully will get it registered by the end of this week

**Comment by epicserve** [comment]
@louy,

Sounds good! If you don't add it to the registry it might be helpful at least to include installation instructions in the README.

**Comment by louy** [comment]
Added here: https://registry.terraform.io/providers/louy/uptimerobot/latest
