### ISSUE TITLE
Please include binary releases 

### ISSUE THREAD

**Issue by drubin** [louy/terraform-provider-uptimerobot#9]
It would be great to include binary releases under the GitHub releases. 

I see there is https://github.com/hashicorp/terraform/issues/18167

But I think uptimerobot needs to officially support this for it to be an official provider?
https://www.terraform.io/guides/terraform-provider-development-program.html 

I see there is currently a failing job on 
https://github.com/louy/terraform-provider-uptimerobot/blob/master/.circleci/config.yml#L37-L44 

Do you require any help with this?

**Comment by louy** [comment]
Yeah I'd love to have that but I haven't really figured out how to get the binary to be built and uploaded to github automatically. Any help would be much appreciated. I'm just finding it difficult to find the time to do it

**Comment by drubin** [comment]
I managed to get it working locally by including `GITHUB_TOKEN` as an ENV variable 

https://goreleaser.com/quick-start/ 

https://github.com/drubin/terraform-provider-uptimerobot/releases/tag/v0.1.1 

I can fiddle a bit more on the `.circleci` configuration, but I just wanted to confirm you tried this? I think

**Comment by louy** [comment]
The issue was more the fact that circleci doesn't build branches by default, which is now fixed in #13. Artifacts are being uploaded to github automatically now. Thanks a lot for your help though! :)

**Comment by drubin** [comment]
@louy Pleasure thanks for starting this!  I been wanting to do this for some time now. Lucky I found your project to contribute to.

**Comment by louy** [comment]
Thanks a lot for contributing, and glad you found it useful ☺️

**Comment by louy** [comment]
@all-contributors please add @drubin for ideas
